### ISSUE TITLE
Implement modulus validation for fødselsnummer

### ISSUE THREAD

**Issue by fagerbua** [mikaello/norwegian-national-id-validator#1]
In the meantime, perhaps add a note in the README file that the library doesn't actually perform a complete validation at present.

**Comment by mikaello** [comment]
Note added.

Actually modulus validation is necessary for D-, H- and FH-number as well. See section 4.2 in the [HIS 1001:2010 standard](https://ehelse.no/identifikatorer-for-personer-syntaks-for-fodselsnummer-hjelpenummer-mv-his-10012010).

**Comment by mikaello** [comment]
Modulus validation is implemented in 50543e14195ff385b1d44e53dd0c6545fa4c63f0 , but this breaks the D-, H- and FH-number tests. 

And it should be some more tests to check the new function.

**Comment by mikaello** [comment]
D-, H- and FH-number tests vere solved in 343ee58fb6f4cfbb6e71280091366c003d41587f, and more tests were added in 8296676e649a36f74a7737e01f5085e8b2e0b72a. Therefore closing this.
