### ISSUE TITLE
Validation fails if user has a weird timezone

### ISSUE THREAD

**Issue by svnv** [mikaello/norwegian-national-id-validator#17]
In `getBirthDate()` a date is created with 
https://github.com/mikaello/norwegian-national-id-validator/blob/18d01f35567dd40ec13b52de98724d8cd20c92ed/src/index.ts#L131-L133

This will cause validation of date to fail if the end user has a non expected timezone in  https://github.com/mikaello/norwegian-national-id-validator/blob/18d01f35567dd40ec13b52de98724d8cd20c92ed/src/index.ts#L18-L30

Example from console log in my IE11 virtual machine
![Screenshot 2019-10-31 at 10 35 33](https://user-images.githubusercontent.com/1080888/67936096-6866a100-fbcb-11e9-958a-f1f7a58da445.png)

**Comment by mikaello** [comment]
I see. So appending `T00:00:00` could solve it? Alternatively use UTC `new Date(Date.UTC(isoStr))`?

**Comment by svnv** [comment]
yes, i have a PR ready in a few minutes
