### ISSUE TITLE
Automatic building of pull requests

### ISSUE THREAD

**Issue by mikaello** [mikaello/norwegian-national-id-validator#19]
Travis should build (and test) new pull requests and leave a comment in the PR with status of the build.

**Comment by cobraz** [comment]
Maybe Github Actions would serve as a better candidate? I can create a Pull Request, if you'd like.

**Comment by mikaello** [comment]
Github Actions seems like a great candidate. No special reason to use Travis, just what I have used in the past. PR is very welcome :-)

**Comment by mikaello** [comment]
Fixed by using the Travis CI GitHub App (which is only available for projects on travis-ci.com). So by converting this project from travis-ci.org to travis-ci.com "Checks" was enabled.
