### ISSUE TITLE
Make age tests general

### ISSUE THREAD

**Issue by mikaello** [mikaello/norwegian-national-id-validator#3]
When testing the age function it is hardcoded what the result will be, e.g. `possibleAgesOfPersonWithIdNumber('04119850938').should.deepEqual([118])`, this will only work until 03.11.2016, after that the test will fail, since the person will turn 119.

**Comment by fatso83** [comment]
You can use `lolex` for this to fake time. No issues then - just fake the clock to be a constant (like March 1 2016)
