### ISSUE TITLE
Invalid Norsk Helsnett test D-Number since 3.0.0

### ISSUE THREAD

**Issue by fungiboletus** [mikaello/norwegian-national-id-validator#33]
Hei,

Since the version 3.0.0 we detect in our tests that a D-Number is not valid anymore : `70019950032`.

This number comes from a Norsk Helsenett test dataset: https://www.nhn.no/media/2606/testaktoerer-v46.pdf
It's the `Testpasient 6`.

Could it be a regression in `norwegian-national-id-validator` or an invalid D-Number in the Norsk Helsenett's dataset ?

Would you be interested to have these test numbers in the unit tests ?

**Comment by mikaello** [comment]
hei!

I'm very interested in having these test numbers in the unit tests. You are very welcome to make a PR, otherwise I can add it when tomorrow or over the weekend.

I don't have time to test or debug tonight. If you got time, could you check if the D-number you found is valid to what I write here: https://github.com/mikaello/norwegian-national-id-validator/issues/30#issuecomment-677903987 ?

**Comment by fungiboletus** [comment]
According to [the official documentation](https://ehelse.no/standarder/identifikatorer-for-personer) ([with an attached PDF](https://ehelse.no/standarder/identifikatorer-for-personer/_/attachment/inline/78f5b271-ca7b-46a9-a2f7-ebaacaf2c2fa:95e4c33fc8e356d02649c6f50bca080247e4cbd5/HITR_1001_2010_Identifikatorer%20for%20personer%20-oppdatert.pdf)), the D-number is valid. `i1 i2 i3 = 5 0 0` and the year is 99, for a (test) person born in 1899.

According to your comment and the 3.0.0 code, it's invalid. In your comment you say "in the code the D number was supposed to have the same rules as the birth number, which is wrong, and therefore a bug." which is contradictory with the official documentation I found.

Where did you find out that D-numbers in the `500-+` range are people born in 2000 or later ?

**Comment by mikaello** [comment]
Hm, I have relied on `Forskrift til folkeregisterloven` , which says in paragraph [§ 2-2-2. D-nummer](https://lovdata.no/forskrift/2017-07-14-1201/§2-2-2):

> Ved tildeling av d-nummer anvendes individsiffer slik:
> a) serien 000–499 anvendes i synkende rekkefølge for personer født før 1. januar 2000,
> b) serien 500–999 anvendes i synkende rekkefølge for personer født etter 1. januar 2000.
> 
> Kvinner skal ha like tall og menn ulike tall som siste individsiffer.
> 
> D-nummeret inaktiveres fem år etter tildeling.

May there be a difference in previous practice and current practice (while this seems to have been the rule for some time, e.g. does this post from 2013 refer to the same: https://lovas.info/2013/12/01/identitetsnummer-i-norge/).

There seems to be a difference between how ehelse.no and lovdata.no defines D-number, or have I misunderstood?

**Comment by fungiboletus** [comment]
Indeed it looks like we have two definitions of the D-number. I would also chose the `Forskrift til folkeregisterloven` definition. Supporting deceased foreigners from the 19th century is not very helpful. And while it's possible, I don't think it's interesting to accept both definitions.

I will add the valid other numbers from the dataset in the unit tests tomorrow.

**Comment by fungiboletus** [comment]
And many thanks for the help and your library !
