### ISSUE TITLE
Why possibleAgesOfPersonWithIdNumber could return more than one age ?

### ISSUE THREAD

**Issue by Zabaa** [mikaello/norwegian-national-id-validator#4]
https://github.com/mikaello/norwegian-national-id-validator/blob/d03063ab125dd46dc46e25b944f741a27e8971b4/src/index.js#L20

Hello. I'm not really sure why this method returns array of numbers instead of concrete age ? I was looking at example from this [post ](https://blog.tedd.no/2016/12/07/norske-fodselsnummer-i-c-norwegian-national-id-numbers-in-c/). In line 115 there's additional verification if year are within allowed range so at the end as a result we can get concrete birthdate.

Regards

**Comment by mikaello** [comment]
Thanks for posting the issue! This seem to be a bug.

I have given an answer to this question in issue 6, I am therefore closing this issue.
