### ISSUE TITLE
Tar du pull requests?

### ISSUE THREAD

**Issue by fatso83** [mikaello/norwegian-national-id-validator#5]
Ser den har en del mangler, f.eks. sjekknummervalidering.

**Comment by mikaello** [comment]
Jeg tar gjerne i mot pull requests! Men akkurat sjekknummervalidering tror jeg skal være implementert:

https://github.com/mikaello/norwegian-national-id-validator/blob/d03063ab125dd46dc46e25b944f741a27e8971b4/src/index.js#L86-L103

Men utvid gjerne testene med et eksempel som beviser det motsatte :-)
